import type { Metadata } from 'next'
import { Geologica } from 'next/font/google'

import { StoreProvider } from './lib/hooks/useStore/StoreProvider'

import '@/app/lib/assets/styles/index.sass'


const geologica = Geologica({
  variable: '--font-geologica',
  subsets: ['latin', 'cyrillic'],
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>

      </head>
      <body className={`${geologica.variable}`}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
